### ISSUE TITLE
Reconfigure project as Spring Boot Application

### ISSUE THREAD

**Issue by shishkovilja** [khasang/businessassistant#46]
We need to change a structure of the BA to run under Spring Boot

**Comment by IMozgg** [comment]
Илья, ты будеш заниматься переводом на SpringBoot?

**Comment by shishkovilja** [comment]
> Илья, ты будеш заниматься переводом на SpringBoot?

мы все, кто сможет, не забывай, что основная связь в Slack и Skype

**Comment by shishkovilja** [comment]
UPDATE: branch feature/ba-0046 contains changes of project providing migration to Spring Boot. Changes saves structure of the project very close to old one, i.e. ServletContext initializer, Web Configurer and Spring Web MVC conrollers instead of using REST controllers of Spring Boot.
To run project you should create Maven configuration because of JPS/JSTL support necessity.

**NOTE: We all have to submit that project runs correctly over all participants environments in order to close issue and make pull request**

**Comment by shishkovilja** [comment]
Received confirmation to merge with development from Boris. Old project structure saved in archive branch archive.development(spring_core)
