### ISSUE TITLE
Changing template engine from JSP to Thymeleaf or FreeMaker

### ISSUE THREAD

**Issue by shishkovilja** [khasang/businessassistant#48]
We have to change **deprecated** JSP web temlates engine. On my opinion, the most evident candidate is Thymeleaf engine, because of official support by Spring Boot

**Comment by IMozgg** [comment]
Maybe Freemarker?

**Comment by shishkovilja** [comment]
I think, that, unfortunately,  template engines aren'n actual now...

**Comment by shishkovilja** [comment]
Propose to close, because we should use Angular 2 or React.js

**Comment by shishkovilja** [comment]
Closed as unnecessary
